name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: sudo apt update && sudo apt install swig doxygen r-base-core libboost-dev cmake libgsl-dev python3-setuptools python3-nose python3-numpy python3-scipy
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: build
      run: cd build && make && sudo make install-python
    - name: test
      run: nosetests3
